resolver: lts-7.15
packages:
    - .
extra-deps:
    - base58-bytestring-0.1.0
    - aeson-quick-0.1.1.2
    - cryptoconditions-0.1.0.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

ghc-options:
    bigchaindb: -lHSrts-ghc8.0.1

